[themeConfig]
repo = "https://github.com/dxx/finders"
docsDir = "docs"
smoothScroll = true

[locales."/"]
lang = "en-US"
title = "Finders"
description = "Distributed service management"


[themeConfig.locales."/"]
selectText = "Languages"
label = "English"
ariaLabel = "Select language"
lastUpdated = "Last Updated"

nav = [
  { text = "Guide", link = "/guide/" }
]

sidebar = [
  { title = "Guide", collapsable = false, sidebarDepth = 1, children = [
    { title = "Introduction", path = "/guide/" },
    { title = "Getting Started", path = "/guide/getting-started" },
  ] },
  { title = "Open API", collapsable = false, children = [
    { title = "Instance API", path = "/guide/instance-api" }
  ] }
]

[locales."/zh/"]
lang = "zh-CN"
title = "Finders"
description = "分布式服务管理"

[themeConfig.locales."/zh/"]
selectText = "选择语言"
label = "简体中文"
ariaLabel = "选择语言"
lastUpdated = "上次更新"

nav = [
  { text = "指南", link = "/zh/guide/" }
]

sidebar = [
  { title = "指南", collapsable = false, sidebarDepth = 1, children = [
    { title = "介绍", path = "/zh/guide/" },
    { title = "快速开始", path = "/zh/guide/getting-started" },
  ] },
  { title = "Open API", collapsable = false, children = [
    { title = "实例接口", path = "/zh/guide/instance-api" }
  ] }
]
