[server]
# Server listening port.
port = 9080

# TCP client connection queue size. Default is 128.
# backlog = 128

# Upper capacity limit of the tcp receiving buffer, the unit is bytes. Default is 128K.
# rcvBuf = 131072

# Upper capacity limit of the tcp send buffer, the unit is bytes. Default is 128K.
# sndBuf = 131072
